import { createFileRoute } from '@tanstack/react-router';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { toast } from 'sonner';
import { supabase } from '@/integrations/supabase/client';
import { useSelection } from '@/lib/selection';
import { PARAMETROS, SEM_MEDICAO, elapsed, fmt, fmtDH, tipoEvento, type Medicao, type Evento } from '@/lib/model';

export const Route=createFileRoute('/_authenticated/painel')({component:Panel});
function lastValue(rows:Medicao[],key:string){if(key==='tan'){const r=rows.find(x=>x.tan_min!=null||x.tan_max!=null);if(!r)return null;const a=r.tan_min??r.tan_max,b=r.tan_max??r.tan_min;return {text:a===b?fmt(a):`${fmt(a)} – ${fmt(b)}`,at:r.medido_em,class:r.classificacao};}const r=rows.find(x=>x[key]!=null);return r?{text:fmt(Number(r[key]),key==='temperatura'||key==='salinidade'?1:2),at:r.medido_em,class:r.classificacao}:null;}
function Panel(){const sel=useSelection();const qc=useQueryClient();const [busy,setBusy]=useState(false),[systemName,setSystemName]=useState('RAS Experimental 1100 L'),[expName,setExpName]=useState('EXPERIMENTO 01');
 const mq=useQuery({queryKey:['panel-measurements',sel.sistema?.id,sel.experimento?.id],enabled:!!sel.sistema,queryFn:async()=>{let q=supabase.from('measurements').select('*').eq('system_id',sel.sistema!.id).order('medido_em',{ascending:false}).limit(100);if(sel.experimento)q=q.eq('experiment_id',sel.experimento.id);const {data,error}=await q;if(error)throw error;return (data??[]) as Medicao[];}});
 const eq=useQuery({queryKey:['panel-events',sel.sistema?.id,sel.experimento?.id],enabled:!!sel.sistema,queryFn:async()=>{let q=supabase.from('events').select('*').eq('system_id',sel.sistema!.id).order('ocorrido_em',{ascending:false}).limit(20);if(sel.experimento)q=q.eq('experiment_id',sel.experimento.id);const {data,error}=await q;if(error)throw error;return (data??[]) as Evento[];}});
 async function createSystem(e:React.FormEvent){e.preventDefault();setBusy(true);const {data:u}=await supabase.auth.getUser();const {data,error}=await supabase.from('ras_systems').insert({user_id:u.user!.id,nome:systemName,especie:'Litopenaeus vannamei',volume_cultivo_l:1000,volume_hidraulico_total_l:1100,salinidade_planejada_ppt:5,estoque_planejado:1000,observacoes:'Modelo inicial PLANEJADO — valores editáveis; não representam medições.'}).select().single();setBusy(false);if(error)return toast.error(error.message);localStorage.setItem('ras:sistema',data.id);toast.success('Sistema RAS criado como planejamento.');sel.recarregar();}
 async function createExp(e:React.FormEvent){e.preventDefault();if(!sel.sistema)return;setBusy(true);const {data:u}=await supabase.auth.getUser();const {data,error}=await supabase.from('experiments').insert({user_id:u.user!.id,system_id:sel.sistema.id,nome:expName,objetivo:'Descobrir limites reais do sistema experimental',status:'NAO_INICIADO'}).select().single();setBusy(false);if(error)return toast.error(error.message);localStorage.setItem('ras:experimento',data.id);toast.success('Experimento criado. Ainda não iniciado.');sel.recarregar();}
 async function start(){if(!sel.experimento)return;const {error}=await supabase.from('experiments').update({status:'EM_ANDAMENTO',iniciado_em:new Date().toISOString()}).eq('id',sel.experimento.id);if(error)return toast.error(error.message);toast.success('Experimento iniciado: DIA 0.');await qc.invalidateQueries();sel.recarregar();}
 if(sel.sistemas.length===0)return <section className="max-w-2xl mx-auto"><div className="label">Primeiro acesso</div><h1 className="text-2xl font-semibold">Bem-vindo ao RAS Digital Twin</h1><p className="muted">Crie o primeiro sistema. O modelo abaixo contém somente valores <b>PLANEJADOS</b>; nenhuma medição será criada.</p><form className="card mt-4" onSubmit={createSystem}><label><span className="label">Nome</span><input className="input mt-1" value={systemName} onChange={e=>setSystemName(e.target.value)}/></label><div className="grid sm:grid-cols-2 gap-3 mt-3 text-sm"><div>Tanque de cultivo: <b>1000 L · PLANEJADO</b></div><div>Volume hidráulico: <b>1100 L · PLANEJADO</b></div><div>Salinidade-alvo: <b>5 ppt · PLANEJADO</b></div><div>Estoque: <b>1000 PL · PLANEJADO</b></div></div><button className="btn mt-4" disabled={busy}>Criar meu sistema RAS</button></form></section>;
 if(sel.experimentos.length===0)return <section className="max-w-2xl"><div className="label">{sel.sistema?.nome}</div><h1 className="text-2xl font-semibold">Criar primeiro experimento</h1><form className="card mt-4" onSubmit={createExp}><label><span className="label">Nome</span><input className="input mt-1" value={expName} onChange={e=>setExpName(e.target.value)}/></label><button className="btn mt-4" disabled={busy}>Criar experimento</button></form></section>;
 const rows=mq.data??[],events=eq.data??[];const population=events.filter(e=>['POVOAMENTO','MORTALIDADE','DESPESCA'].includes(e.tipo)).reduce((n,e)=>n+(e.tipo==='POVOAMENTO'?1:-1)*(e.quantidade??0),0);
 return <section><div className="flex flex-wrap gap-3 justify-between items-end"><div><div className="label">Visão geral operacional</div><h1 className="text-2xl font-semibold m-0">{sel.sistema?.nome}</h1><p className="muted text-sm">{sel.experimento?.nome} · {sel.experimento?.iniciado_em?'experimento em acompanhamento':'ainda não iniciado'}</p></div>{sel.experimento&&!sel.experimento.iniciado_em&&<button className="btn" onClick={start}>INICIAR EXPERIMENTO · DIA 0</button>}</div><div className="grid grid-cols-2 lg:grid-cols-4 gap-3 mt-5">{PARAMETROS.map(([key,label,unit])=>{const v=lastValue(rows,key);return <div className="card" key={key}><div className="label">{label}</div>{v?<><div className="reading text-xl mt-2">{v.text}{unit&&<small className="text-xs ml-1 muted">{unit}</small>}</div><div className="mt-2 flex gap-2 items-center"><span className="badge">{v.class}</span><span className="text-xs muted">{elapsed(v.at)}</span></div></>:<div className="mt-3 font-semibold muted">{SEM_MEDICAO}</div>}</div>})}</div><div className="grid md:grid-cols-3 gap-3 mt-3"><div className="card"><div className="label">Camarões ativos</div><div className="reading text-xl mt-2">{Math.max(0,population)}</div><p className="muted text-xs">Calculado apenas a partir de eventos de povoamento, mortalidade e despesca.</p></div><div className="card"><div className="label">Salinidade-alvo</div><div className="reading text-xl mt-2">{fmt(sel.sistema?.salinidade_planejada_ppt,1)} ppt</div><span className="badge">PLANEJADO</span></div><div className="card"><div className="label">Gêmeo digital</div><div className="font-semibold mt-2">Dados insuficientes para calibração</div><p className="muted text-xs">Nenhuma previsão é inventada para preencher a tela.</p></div></div><div className="mt-6"><h2 className="text-lg font-semibold">Timeline recente</h2><div className="card p-0 overflow-hidden">{[...rows.slice(0,6).map(r=>({t:r.medido_em,k:'MEDIÇÃO',d:'Medição registrada'})),...events.slice(0,10).map(e=>({t:e.ocorrido_em,k:'EVENTO',d:tipoEvento(e.tipo)}))].sort((a,b)=>b.t.localeCompare(a.t)).slice(0,12).map((x,i)=><div key={`${x.t}${i}`} className="flex gap-3 p-3 border-b last:border-0"><span className="badge">{x.k}</span><div><b className="text-sm">{x.d}</b><div className="muted text-xs">{fmtDH(x.t)}</div></div></div>)}{rows.length===0&&events.length===0&&<div className="p-5 muted">Nenhuma medição ou evento registrado.</div>}</div></div></section>}
