import { Link, useNavigate, useRouterState } from "@tanstack/react-router";
import { Activity, Beaker, Database, FlaskConical, LogOut, Menu, Waves } from "lucide-react";
import { useState, type ReactNode } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useSelection } from "@/lib/selection";
import { diaExperimental } from "@/lib/model";
import { MeasurementDialog } from "./MeasurementDialog";
import { EventDialog } from "./EventDialog";

const nav=[['/painel','Visão geral',Activity],['/qualidade-agua','Qualidade da água',Waves],['/eventos','Eventos / Timeline',Beaker],['/historico','Histórico / CSV',Database],['/mbbr','MBBR',FlaskConical],['/lotes','Lotes',Beaker],['/gemeo-digital','Gêmeo digital',Activity],['/perfil','Perfil',Activity]] as const;
export function AppShell({children}:{children:ReactNode}){
 const {sistemas,sistema,experimentos,experimento,selecionarSistema,selecionarExperimento}=useSelection(); const path=useRouterState({select:s=>s.location.pathname}); const navg=useNavigate(); const [open,setOpen]=useState(false);
 const dia=diaExperimental(experimento?.iniciado_em??null);
 async function sair(){await supabase.auth.signOut();navg({to:"/auth",replace:true});}
 const sidebar=<><div className="px-4 py-4 flex gap-2 items-center"><FlaskConical size={20}/><div><b className="text-sm">RAS DIGITAL TWIN</b><div className="text-[10px] opacity-65 uppercase">Litopenaeus vannamei</div></div></div><nav className="p-2 space-y-1">{nav.map(([to,label,Icon])=><Link key={to} to={to as never} onClick={()=>setOpen(false)} className={`flex items-center gap-2 rounded-md px-3 py-2 text-sm ${path===to?"bg-white/15 font-semibold":"hover:bg-white/10"}`}><Icon size={15}/>{label}</Link>)}</nav></>;
 return <div className="min-h-screen"><aside className="hidden lg:block fixed inset-y-0 left-0 w-60 bg-slate-800 text-slate-100 overflow-auto">{sidebar}</aside>{open&&<div className="fixed inset-0 z-50 lg:hidden"><button className="absolute inset-0 bg-black/40 w-full" onClick={()=>setOpen(false)} aria-label="Fechar menu"/><aside className="relative w-64 h-full bg-slate-800 text-slate-100">{sidebar}</aside></div>}<div className="lg:pl-60"><header className="sticky top-0 z-30 bg-white/95 backdrop-blur border-b px-3 py-2 flex gap-2 items-center"><button className="btn secondary lg:hidden" onClick={()=>setOpen(true)}><Menu size={16}/></button><div className="flex-1 flex flex-wrap gap-2">{sistemas.length>0&&<select className="input max-w-52" value={sistema?.id??""} onChange={e=>selecionarSistema(e.target.value)}>{sistemas.map(s=><option key={s.id} value={s.id}>{s.nome}</option>)}</select>}{experimentos.length>0&&<select className="input max-w-52" value={experimento?.id??""} onChange={e=>selecionarExperimento(e.target.value)}>{experimentos.map(x=><option key={x.id} value={x.id}>{x.nome}</option>)}</select>}{experimento&&<span className="badge self-center">{dia==null?"NÃO INICIADO":`DIA ${dia}`} · {experimento.status.replaceAll("_"," ")}</span>}</div><div className="hidden md:flex gap-2"><MeasurementDialog/><EventDialog/></div><button className="btn secondary" onClick={sair} title="Sair"><LogOut size={15}/></button></header><main className="p-3 sm:p-5 pb-24 md:pb-6">{children}</main></div>{sistema&&<div className="fixed bottom-0 inset-x-0 z-30 md:hidden bg-white border-t p-2 grid grid-cols-2 gap-2"><MeasurementDialog/><EventDialog/></div>}</div>;
}
