import { useState } from "react";
import { useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { useSelection } from "@/lib/selection";
const tipos=[['ADICAO_AMONIA','Adição de amônia','g'],['ADICAO_NACL','Adição de NaCl','g'],['ADICAO_NAHCO3','Adição de NaHCO₃','g'],['ADICAO_AGUA','Adição de água','L'],['RETIRADA_AGUA','Retirada de água','L'],['TROCA_AGUA','Troca de água','L'],['REPOSICAO_EVAPORACAO','Reposição por evaporação','L'],['PURGA_DECANTADOR','Purga do decantador','L'],['LIMPEZA','Limpeza',''],['MUDANCA_VAZAO','Mudança de vazão','L/h'],['MUDANCA_AERACAO','Mudança de aeração','L/min'],['POVOAMENTO','Povoamento','animais'],['ALIMENTACAO','Alimentação','g'],['BIOMETRIA','Biometria',''],['MORTALIDADE','Mortalidade','animais'],['MUDA','Muda',''],['DESPESCA','Despesca','animais'],['OUTRO','Outro','']] as const;
export function EventDialog(){const [open,setOpen]=useState(false),[busy,setBusy]=useState(false);const [tipo,setTipo]=useState('OUTRO'),[q,setQ]=useState(''),[desc,setDesc]=useState(''),[obs,setObs]=useState('');const {sistema,experimento}=useSelection();const qc=useQueryClient();const def=tipos.find(x=>x[0]===tipo)!;
 async function save(e:React.FormEvent){e.preventDefault();if(!sistema)return;const n=q.trim()===''?null:Number(q.replace(',','.'));if(n!=null&&(!Number.isFinite(n)||n<0)){toast.error('Quantidade inválida.');return}if(['POVOAMENTO','MORTALIDADE','DESPESCA'].includes(tipo)&&(n==null||!Number.isInteger(n))){toast.error('Informe uma quantidade inteira de animais.');return}setBusy(true);const {data:u}=await supabase.auth.getUser();const {error}=await supabase.from('events').insert({user_id:u.user!.id,system_id:sistema.id,experiment_id:experimento?.id??null,tipo,ocorrido_em:new Date().toISOString(),quantidade:n,unidade:def[2]||null,descricao:desc||null,observacoes:obs||null,dados:{}});setBusy(false);if(error){toast.error(error.message);return}toast.success('Evento registrado.');setQ('');setDesc('');setObs('');setOpen(false);void qc.invalidateQueries();}
 return <><button className="btn secondary" disabled={!sistema} onClick={()=>setOpen(true)}>Registrar evento</button>{open&&<div className="overlay"><form className="modal max-w-xl" onSubmit={save}><div className="flex justify-between"><h2 className="m-0 text-lg font-semibold">Registrar evento</h2><button type="button" className="btn secondary" onClick={()=>setOpen(false)}>Fechar</button></div><label className="block mt-3"><span className="label">Tipo</span><select className="input mt-1" value={tipo} onChange={e=>setTipo(e.target.value)}>{tipos.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select></label><div className="grid grid-cols-2 gap-3 mt-3"><label><span className="label">Quantidade</span><input className="input mt-1" value={q} onChange={e=>setQ(e.target.value)} /></label><label><span className="label">Unidade</span><input className="input mt-1" value={def[2]} readOnly /></label></div><label className="block mt-3"><span className="label">Descrição</span><input className="input mt-1" value={desc} onChange={e=>setDesc(e.target.value)}/></label><label className="block mt-3"><span className="label">Observações</span><textarea className="input mt-1" rows={3} value={obs} onChange={e=>setObs(e.target.value)}/></label><div className="flex justify-end mt-4"><button className="btn" disabled={busy}>{busy?'Salvando...':'Salvar evento'}</button></div></form></div>}</>}
