import { useState } from "react";
import { useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { useSelection } from "@/lib/selection";

const fields=[['no2','NO₂','mg/L',0,999],['no3','NO₃','mg/L',0,9999],['ph','pH','',0,14],['temperatura','Temperatura','°C',-5,60],['alcalinidade','Alcalinidade','mg/L CaCO₃',0,9999],['salinidade','Salinidade','ppt',0,100],['oxigenio_dissolvido','Oxigênio dissolvido','mg/L',0,30],['orp','ORP','mV',-2000,2000],['tss','TSS','mg/L',0,99999],['turbidez','Turbidez','NTU',0,99999],['dureza','Dureza','mg/L CaCO₃',0,99999],['ca','Ca','mg/L',0,99999],['mg','Mg','mg/L',0,99999],['k','K','mg/L',0,99999],['na','Na','mg/L',0,99999],['cl','Cl','mg/L',0,99999]] as const;
const dec=(v:string)=>v.trim()===''?null:Number(v.replace(',','.'));
export function MeasurementDialog(){const [open,setOpen]=useState(false);const [busy,setBusy]=useState(false);const [vals,setVals]=useState<Record<string,string>>({});const {sistema,experimento}=useSelection();const qc=useQueryClient();
 async function save(e:React.FormEvent){e.preventDefault();if(!sistema)return;const tmin=dec(vals.tan_min??''),tmax=dec(vals.tan_max??'');if((tmin!=null&&!Number.isFinite(tmin))||(tmax!=null&&!Number.isFinite(tmax))){toast.error('TAN inválido.');return}if((tmin!=null&&tmin<0)||(tmax!=null&&tmax<0)){toast.error('TAN não pode ser negativo.');return}if(tmin!=null&&tmax!=null&&tmin>tmax){toast.error('TAN mínimo não pode ser maior que o máximo.');return}
 const row:Record<string,unknown>={tan_min:tmin??tmax,tan_max:tmax??tmin};let any=tmin!=null||tmax!=null;for(const [key,label,,min,max] of fields){const n=dec(vals[key]??'');if(n==null)continue;if(!Number.isFinite(n)||n<min||n>max){toast.error(`${label}: valor inválido.`);return}row[key]=n;any=true}if(!any){toast.error('Informe pelo menos um parâmetro realmente medido.');return}setBusy(true);const {data:u}=await supabase.auth.getUser();const {error}=await supabase.from('measurements').insert({...row,user_id:u.user!.id,system_id:sistema.id,experiment_id:experimento?.id??null,medido_em:new Date().toISOString(),classificacao:'MEDIDO',metodo:vals.metodo||null,instrumento:vals.instrumento||null,local_coleta:vals.local||null,observacoes:vals.obs||null});setBusy(false);if(error){toast.error(error.message);return}toast.success('Medição registrada.');setVals({});setOpen(false);void qc.invalidateQueries();}
 return <><button className="btn" disabled={!sistema} onClick={()=>setOpen(true)}>Registrar medição</button>{open&&<div className="overlay"><form className="modal" onSubmit={save}><div className="flex justify-between gap-3"><div><h2 className="m-0 text-lg font-semibold">Registrar medição</h2><p className="muted text-sm">Preencha somente o que foi realmente medido.</p></div><button type="button" className="btn secondary" onClick={()=>setOpen(false)}>Fechar</button></div><div className="card bg-slate-50 mt-3"><div className="label">TAN — preservar intervalo colorimétrico</div><div className="grid grid-cols-2 gap-2 mt-2"><input className="input" placeholder="mínimo, ex.: 1,5" value={vals.tan_min??''} onChange={e=>setVals(v=>({...v,tan_min:e.target.value}))}/><input className="input" placeholder="máximo, ex.: 2,5" value={vals.tan_max??''} onChange={e=>setVals(v=>({...v,tan_max:e.target.value}))}/></div></div><div className="grid grid-cols-2 sm:grid-cols-3 gap-3 mt-3">{fields.map(([key,label,unit])=><label key={key}><span className="label">{label}{unit?` (${unit})`:''}</span><input className="input mt-1" inputMode="decimal" value={vals[key]??''} onChange={e=>setVals(v=>({...v,[key]:e.target.value}))}/></label>)}</div><div className="grid sm:grid-cols-3 gap-3 mt-3">{[['metodo','Método'],['instrumento','Instrumento / teste'],['local','Local da coleta']].map(([k,l])=><label key={k}><span className="label">{l}</span><input className="input mt-1" value={vals[k]??''} onChange={e=>setVals(v=>({...v,[k]:e.target.value}))}/></label>)}</div><label className="block mt-3"><span className="label">Observações</span><textarea className="input mt-1" rows={3} value={vals.obs??''} onChange={e=>setVals(v=>({...v,obs:e.target.value}))}/></label><div className="flex justify-end gap-2 mt-4"><button type="button" className="btn secondary" onClick={()=>setOpen(false)}>Cancelar</button><button className="btn" disabled={busy}>{busy?'Salvando...':'Salvar medição'}</button></div></form></div>}</>}
